### ISSUE TITLE
Which hmac library did you use?

### ISSUE THREAD

**Issue by mvanholsteijn** [grosskur/lua-resty-aws#1]
Hi,

Your module looks like a really nice and elegant solution for reverse proxying to a s3 bucket,  but it does not appear to work with the lua-resty-hmac. Can you tell me which library you used?

In particular: your code calls hmac:new(), which requires a secret key as a parameter in the lua-resty-hmac module.

Cheers,

Mark

**Comment by grosskur** [comment]
Thanks! Yes, I created this module specifically to reverse proxy an S3 bucket.

Sorry, I forgot to document the dependencies. I used [hmac.lua](https://github.com/ddragosd/lua-resty-string/blob/master/lib/resty/hmac.lua) from [ddragosd/lua-resty-string](https://github.com/ddragosd/lua-resty-string).

See also the discussion in openresty/lua-resty-string#18. Specifically, they mention [adobe-apiplatform/api-gateway-aws](https://github.com/adobe-apiplatform/api-gateway-aws), which might be another option for you.
